spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garacar
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api

file:
  upload-dir: E:\GaraCarProject\image\

