const constantObject = {
    
    FETCH_ALL_GROUP_CHAT_ADMIN: 'FETCH_ALL_GROUP_CHAT_ADMIN',
    FETCH_ALL_MESSAGE_IN_GROUP:'FETCH_ALL_MESSAGE_IN_GROUP',
    NOTIFICATION_MESSAGE: 'NOTIFICATION_MESSAGE',
    RECENTLY_CONNECTION: 'RECENTLY_CONNECTION',
    SEND_MESSAGE: 'SEND_MESSAGE',


    //Responsive Constant
    MOBILE_VIEWPORT_PX: 550,
};

export default constantObject;
